// Generated by CoffeeScript 1.6.3
(function() {
  var heroes;

  heroes = require('./controllers/heroes');

  module.exports = function(app, router) {
    router.get('/', function(req, res) {
      return res.render('index');
    });
    app.route('/api/heroes').get(function(req, res) {
      return heroes.index(req, res);
    }).post(function(req, res) {
      return heroes.add(req, res);
    });
    return app.route('/api/heroes/:id').get(function(req, res) {
      return heroes.get(req, res);
    }).put(function(req, res) {
      return heroes.update(req, res);
    })["delete"](function(req, res) {
      return heroes["delete"](req, res);
    });
  };

}).call(this);
