// Generated by CoffeeScript 1.6.3
(function() {
  var Hero, Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  Hero = new Schema({
    heroId: Number,
    battleTag: String,
    name: String,
    "class": String,
    level: Number,
    paragonLevel: Number
  }, {
    collection: 'heroes'
  });

  mongoose.model('Hero', Hero);

}).call(this);
