// Generated by CoffeeScript 1.6.3
(function() {
  var app, bodyParser, connect, connection_string, express, ipaddress, mongoose, path, port, router, routes;

  connect = require('connect');

  express = require('express');

  path = require('path');

  bodyParser = require('body-parser');

  routes = require('./app/routes');

  mongoose = require('mongoose');

  app = express();

  ipaddress = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1';

  port = process.env.OPENSHIFT_NODEJS_PORT || 8080;

  if (process.env.OPENSHIFT_MONGODB_DB_PASSWORD) {
    connection_string = "" + process.env.OPENSHIFT_MONGODB_DB_USERNAME + ":" + process.env.OPENSHIFT_MONGODB_DB_PASSWORD + "@" + process.env.OPENSHIFT_MONGODB_DB_HOST + ":" + process.env.OPENSHIFT_MONGODB_DB_PORT + "/" + process.env.OPENSHIFT_APP_NAME;
  } else {
    connection_string = 'localhost/d3';
  }

  app.use(bodyParser());

  app.use('/', express["static"](path.join(__dirname, 'public')));

  app.set('views', __dirname + '/app/views');

  app.set('view engine', 'hbs');

  mongoose.connect("mongodb://" + connection_string);

  mongoose.connection.on('open', function() {
    return console.log('Connected to MongoDB...');
  });

  router = express.Router();

  routes(app, router);

  app.use('/', router);

  app.listen(port, ipaddress, function() {
    return console.log('Server up');
  });

}).call(this);
